version: '3.8'

services:
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./data:/data
    environment:
      KEY: mysupersecretkey
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: admin123
      DB_CLIENT: sqlite3
      DB_FILENAME: /data/database.db
